default_values:
  sell_trade_priority_expression: ${DEFAULT_SELL_TRADE_PRIORITY_EXPRESSION:if price<0 then return 0$if time==null then return null$if minSellPrice<0 then return -9223372036854775808$if monthMedianPrice==null then monthMedianPrice=0$priceFactor=price^0.5$priceDifferenceFactor=(price-medianPrice)$if medianPrice==0 then priceDifferenceFactor=1$if priceDifferenceFactor<0 then priceDifferenceFactor=priceDifferenceFactor*(-1)$if priceDifferenceFactor<1 then priceDifferenceFactor=1$priceRatioFactorPercent=(price-monthMedianPrice)*100/medianPrice$if monthMedianPrice==0 then priceRatioFactorPercent=1$if priceRatioFactorPercent<0 then priceRatioFactorPercent=priceRatioFactorPercent*(-1)$if priceRatioFactorPercent<1 then priceRatioFactorPercent=1&if monthSales==null then sales=0$if monthSales!=null then sales=monthSales$timeFactor=43200/(time^0.4)$tradePriority=priceFactor*priceDifferenceFactor*priceRatioFactorPercent*timeFactor$if price<monthMedianPrice then tradePriority=tradePriority*(-1)$return tradePriority}
  buy_trade_priority_expression: ${DEFAULT_BUY_TRADE_PRIORITY_EXPRESSION:if price<0 then return 0$if time==null then return null$if monthMedianPrice==null then monthMedianPrice=0$priceFactor=price^0.8$priceDifferenceFactor=(price-medianPrice)$if medianPrice==0 then priceDifferenceFactor=1$if priceDifferenceFactor<0 then priceDifferenceFactor=priceDifferenceFactor*(-1)$if priceDifferenceFactor<1 then priceDifferenceFactor=1$priceRatioFactorPercent=(price-monthMedianPrice)*100/medianPrice$if monthMedianPrice==0 then priceRatioFactorPercent=1$if priceRatioFactorPercent<0 then priceRatioFactorPercent=priceRatioFactorPercent*(-1)$if priceRatioFactorPercent<1 then priceRatioFactorPercent=1&if monthSales==null then sales=0$if monthSales!=null then sales=monthSales$timeToResellFactor=sales^0.7$timeFactor=43200/(time^0.8)$tradePriority=priceFactor*priceDifferenceFactor*priceRatioFactorPercent*timeToResellFactor*timeFactor$if price>monthMedianPrice then tradePriority=tradePriority*(-1)$return tradePriority}

ubi:
  urls:
    graphql: ${UBI_GRAPHQL_URL:https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    baseAppId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    dateFormat: ${UBI_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    itemSaleStatsDateFormat: ${UBI_ITEM_SALE_DATE_FORMAT:yyyy-MM-dd}
    minUncommonPrice: ${UBI_MIN_UNCOMMON_PRICE:10}
    maxUncommonPrice: ${UBI_MAX_UNCOMMON_PRICE:25000}
    minRarePrice: ${UBI_MIN_RARE_PRICE:10}
    maxRarePrice: ${UBI_MAX_RARE_PRICE:250000}
    minEpicPrice: ${UBI_MIN_EPIC_PRICE:10}
    maxEpicPrice: ${UBI_MAX_EPIC_PRICE:1000000}
    minLegendaryPrice: ${UBI_MIN_LEGENDARY_PRICE:10}
    maxLegendaryPrice: ${UBI_MAX_LEGENDARY_PRICE:1000000}

server:
  port: ${SERVER_PORT:8088}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    fixedRate: ${SCHEDULING_FIXED_DELAY:60000}
    initialDelay: ${SCHEDULING_INITIAL_DELAY:0}

logging:
  level:
    github: \${logging_level:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper
  data:
    redis:
      repositories:
        enabled: false
      url: redis://${REDIS_SERVER_HOST:localhost}:${REDIS_SERVER_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_HOST:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1
    properties:
      request.timeout.ms: 3000
  config:
    import:
      - test-values.yaml