auth:
  user_service:
    password:
      encryption:
        key: ${PASSWORD_ENCRYPTION_KEY} #AES Key

ubi:
  urls:
    authorization: ${UBI_AUTH_URL:https://public-ubiservices.ubi.com/v3/profiles/sessions}
    twoFaCodeToSMS: ${UBI_TWO_FA_CODE_TO_SMS_URL:https://public-ubiservices.ubi.com/v3/profiles/me/2facode}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    twoFaAppId: ${UBI_2FA_APP_ID:685a3038-2b04-47ee-9c5a-6403381a46aa}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    trustedDeviceId: ${UBI_TRUSTED_DEVICE_ID:16a2c7f446d2fcb5b92d0efee317da39}
    trustedDeviceFriendlyName: ${UBI_TRUSTED_DEVICE_FRIENDLY_NAME:Opera 114.0.0.0, Windows 10}

server:
  port: ${SERVER_PORT:8090}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    fixedRate: ${SCHEDULING_FIXED_DELAY:9000000}
    initialDelay: ${SCHEDULING_INITIAL_DELAY:0}
    # every 2.5h after 1.5m of delay

logging:
  level:
    github: ${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper-users-ubi-accs-reauthorizer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_HOST:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1
    properties:
      request.timeout.ms: 3000

  config:
    import:
      - auth-values.yaml
      - test-values.yaml