auth:
  ubi_credentials:
    expireTimeout: ${UBI_AUTH_EXPIRE_TIMEOUT:10500} # seconds, 3 hours - 5min. Ubisoft's session expires in 3 hours

ubi:
  urls:
    authorization: ${UBI_AUTH_URL:https://public-ubiservices.ubi.com/v3/profiles/sessions}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    baseAppId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}

server:
  port: ${SERVER_PORT:8078}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    fixedRate: ${SCHEDULING_FIXED_DELAY:9000000}
    initialDelay: ${SCHEDULING_INITIAL_DELAY:0}
    # every 2.5h

logging:
  level:
    github: \${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper-fetching_accounts_reauthorizer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import:
      - test-values.yaml