version: '2.4'

services:

 postgres:
    container_name: r6helper-postgres
    image: postgres:16.3
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=r6helper
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
     - postgres-net
    restart: always

 neo4j:
    container_name: r6helper-neo4j
    image: neo4j:ubi9
    ports:
     - "7474:7474"
     - "7687:7687"
    environment:
     - NEO4J_AUTH=neo4j/password
    volumes:
     - neo4j-data:/data
     - neo4j-logs:/logs
     - neo4j-import:/var/lib/neo4j/import
     - neo4j-plugins:/plugins
    networks:
     - neo4j-net
    restart: always

 neo4j-test:
   container_name: r6helper-neo4j-test
   image: neo4j:ubi9
   ports:
     - "7475:7474"
     - "7688:7687"
   environment:
     - NEO4J_AUTH=neo4j/password
   volumes:
     - test-neo4j-data:/data
     - test-neo4j-logs:/logs
     - test-neo4j-import:/var/lib/neo4j/import
     - test-neo4j-plugins:/plugins
   networks:
     - neo4j-net

 redis:
    container_name: r6helper-redis
    image: redis:7.2.4-bookworm
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
     - redis-net
    restart: always

 redis-test:
   container_name: r6helper-redis-test
   image: redis:7.2.4-bookworm
   ports:
     - "6380:6379"
   volumes:
     - test-redis-data:/data
   networks:
     - redis-net

 zipkin:
    container_name: r6helper-zipkin
    image: openzipkin/zipkin:3.1.0
    ports:
     - "9411:9411"
    networks:
     - zipkin-net
    restart: always

networks:
    postgres-net:
    neo4j-net:
    zipkin-net:
    redis-net:

volumes:
 postgres-data:
 neo4j-data:
 neo4j-logs:
 neo4j-import:
 neo4j-plugins:
 redis-data:

 test-neo4j-data:
 test-neo4j-logs:
 test-neo4j-import:
 test-neo4j-plugins:
 test-redis-data: