services:

  configs_fetcher:
    container_name: r6helper-configs-fetcher
    build:
      context: .
      dockerfile: configs_fetcher/Dockerfile
    image: r6helper-configs-fetcher
    ports:
      - "8091:8082"
    networks:
      - postgres-net
      - redis-net
    restart: always

  item_day_sales_ubi_stats_fetcher:
    container_name: r6helper-item-day-sales-ubi-stats-fetcher
    build:
      context: .
      dockerfile: item_day_sales_ubi_stats_fetcher/Dockerfile
    image: r6helper-item-day-sales-ubi-stats-fetcher
    ports:
      - "8092:8083"
    networks:
      - postgres-net
      - redis-net
    restart: always

  items_stats_fetcher:
    container_name: r6helper-item-stats-fetcher
    build:
      context: .
      dockerfile: item_stats_fetcher/Dockerfile
    image: r6helper-item-stats-fetcher
    ports:
      - "8093:8081"
    networks:
      - postgres-net
      - redis-net
    restart: always

  item_trade_stats_calculator:
    container_name: r6helper-item-trade-stats-calculator
    build:
      context: .
      dockerfile: item_trade_stats_calculator/Dockerfile
    image: r6helper-item-trade-stats-calculator
    ports:
      - "8094:8085"
    networks:
        - postgres-net
        - redis-net
    restart: always

  main_user_reauthorizer:
    container_name: r6helper-main-user-reauthorizer
    build:
      context: .
      dockerfile: main_user_reauthorizer/Dockerfile
    image: r6helper-main-user-reauthorizer
    ports:
      - "8095:8084"
    networks:
      - postgres-net
      - redis-net
    restart: always

  notifications_service:
    container_name: r6helper-notifications-service
    build:
      context: .
      dockerfile: notifications_service/Dockerfile
    image: r6helper-notifications-service
    ports:
      - "8096:8089"
    networks:
      - postgres-net
      - redis-net
      - kafka-net
    restart: always


  postgres:
    container_name: r6helper-postgres
    command: postgres -c 'max_connections=300'
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    restart: always

  pgadmin:
    container_name: r6helper-pgadmin
    image: dpage/pgadmin4:8.12
    ports:
      - "5050:80"
    networks:
      - postgres-net
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    restart: always

  redis:
    container_name: r6helper-redis
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    restart: always

  redis-test:
    container_name: r6helper-redis-test
    image: redis:7.2.4-bookworm
    ports:
      - "6380:6379"
    volumes:
      - test-redis-data:/data
    networks:
      - redis-net
    restart: always

  kafka:
    container_name: r6helper-kafka
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_MOUNTED_CONF_DIR=/bitnami/kafka/config
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@r6helper-kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9091,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://r6helper-kafka:9091,CONTROLLER://r6helper-kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - kafka-net

networks:
  postgres-net:
  zipkin-net:
  redis-net:
  kafka-net:

volumes:
  postgres-data:
  redis-data:
  test-redis-data:
  kafka-data:
