ubi:
  urls:
    graphql: ${UBI_GRAPHQL_URL:https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    baseAppId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    dateFormat: ${UBI_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    itemSaleStatsDateFormat: ${UBI_ITEM_SALE_DATE_FORMAT:yyyy-MM-dd}

server:
  port: ${SERVER_PORT:8082}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    fixedRate: ${SCHEDULING_FIXED_DELAY:86400000}
    initialDelay: ${SCHEDULING_INITIAL_DELAY:180000}
    # every 24h after 3m of delay

logging:
  level:
    github: \${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper-item_day_sales_ubi_stats_fetcher
  data:
    redis:
      repositories:
        enabled: false
      url: redis://${REDIS_SERVER_HOST:localhost}:${REDIS_SERVER_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import:
      - test-values.yaml