auth:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}
  ubi_credentials:
    platform: ${UBI_PLATFORM:UPLAY}
    email: ${UBI_EMAIL}
    password: ${UBI_PASSWORD}
    expireTimeout: ${UBI_EXPIRE_TIMEOUT:9000} # seconds, 2.5 hours. Ubisoft's session expires in 3 hours
  user_service:
    password:
      encryption:
        key: ${PASSWORD_ENCRYPTION_KEY} #AES Key

ubi:
  urls:
    updateItems: https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql
    authorization: https://public-ubiservices.ubi.com/v3/profiles/sessions
  session:
    contentType: application/json
    userAgent: UbiServices_SDK_2020.Release.58_PC64_ansi_static
    appId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    expireTimeout: ${auth.ubi_credentials.expireTimeout}

server:
  port: 8080

spring:
  application:
    name: r6s-helper
  config:
    import:
      - auth-values.yaml
  data:
    redis:
      repositories:
        enabled: false
      url: redis://localhost:6379
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_AUTH_USERNAME:neo4j}
      password: ${NEO4J_AUTH_PASSWORD:password}

app:
  scheduling:
    enabled: true

logging:
  level:
    github: debug
    org:
      springframework:
        data:
          neo4j:
            cypher:
              unrecognized: off
  file:
    name: ./logs/prod/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0