ubi:
  urls:
    updateItems: https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql
  password:
    encryption:
      key: ${UBI_ENCRYPTION_KEY} #AES Key

  session:
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    appId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    profileId: ${UBI_PROFILE_ID} #User specific, doesnt change
    sessionId: ${UBI_SESSION_ID} #User specific, changed every time, but old can be used
    authorization: ${UBI_AUTHORIZATION} #User specific, expires fast

server:
  port: 8080

spring:
  application:
    name: r6s-helper
  config:
    import:
      - auth-values.yaml

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_AUTH_USERNAME:neo4j}
      password: ${NEO4J_AUTH_PASSWORD:password}


auth:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    github: debug
  file:
    name: ./${spring.application.name}/logs/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0