auth:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}

  ubi_credentials:
    platform: ${UBI_PLATFORM:UPLAY}
    email: ${UBI_EMAIL}
    password: ${UBI_PASSWORD}

  user_service:
    password:
      encryption:
        key: ${PASSWORD_ENCRYPTION_KEY} #AES Key

ubi:
  urls:
    updateItems: https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql
    authorization: 
  session:
    appId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}

server:
  port: 8080

spring:
  application:
    name: r6s-helper

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_AUTH_USERNAME:neo4j}
      password: ${NEO4J_AUTH_PASSWORD:password}

  config:
    import:
      - auth-values.yaml

logging:
  level:
    github: debug
  file:
    name: ./${spring.application.name}/logs/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0