ubi:
  urls:
    updateItems: https://public-ubiservices.ubi.com/v1/profiles/me/uplay/graphql

  session:
    spaceId: ${UBI_SPACE_ID}
    appId: ${UBI_APP_ID}
    authorization: ${UBI_AUTHORIZATION}
    sessionId: ${UBI_SESSION_ID}
    profileId: ${UBI_PROFILE_ID}
    regionId: ${UBI_REGION_ID}
    localeCode: ${UBI_LOCALE_CODE}

server:
  port: 8080

spring:
  application:
    name: r6s-helper
  config:
    import:
      - auth-values.yaml
auth:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}

logging:
  level:
    app: trace
  file:
    name: ./${spring.application.name}/logs/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0