auth:
  ubi_credentials:
    platform: ${UBI_PLATFORM}
    email: ${UBI_EMAIL}
    password: ${UBI_PASSWORD}
    expireTimeout: ${UBI_AUTH_EXPIRE_TIMEOUT:10500} # seconds, 3 hours - 5min. Ubisoft's session expires in 3 hours

ubi:
  urls:
    authorization: ${UBI_AUTH_URL:https://public-ubiservices.ubi.com/v3/profiles/sessions}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    baseAppId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    expireTimeout: ${auth.ubi_credentials.expireTimeout}

server:
  port: ${SERVER_PORT:8085}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    fixedRate: ${SCHEDULING_FIXED_DELAY:9000000}
    initialDelay: ${SCHEDULING_INITIAL_DELAY:0}
    # every 2.5h

logging:
  level:
    github: \${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper-main-user-reauthorizer
  data:
    redis:
      repositories:
        enabled: false
      url: redis://${REDIS_SERVER_HOST:localhost}:${REDIS_SERVER_PORT:6379}

  config:
    import:
      - auth-values.yaml
      - test-values.yaml