auth:
  ubi_credentials:
    platform: ${UBI_PLATFORM:UPLAY}
    email: ${UBI_EMAIL}
    password: ${UBI_PASSWORD}
    expireTimeout: ${UBI_EXPIRE_TIMEOUT:10500} # seconds, 3 hours - 5min. Ubisoft's session expires in 3 hours

ubi:
  urls:
    authorization: https://public-ubiservices.ubi.com/v3/profiles/sessions
  session:
    contentType: application/json
    userAgent: UbiServices_SDK_2020.Release.58_PC64_ansi_static
    baseAppId: ${UBI_APP_ID:80a4a0e8-8797-440f-8f4c-eaba87d0fdda}
    spaceId: ${UBI_SPACE_ID:0d2ae42d-4c27-4cb7-af6c-2099062302bb}
    regionId: ${UBI_REGION_ID:WW}
    localeCode: ${UBI_LOCALE_CODE:en-US}
    expireTimeout: ${auth.ubi_credentials.expireTimeout}

server:
  port: 8084

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}

logging:
  level:
    github: debug
    org:
      springframework:
        data:
          neo4j:
            cypher:
              unrecognized: off
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: r6s-helper-main-user-reauthorizer
  data:
    redis:
      repositories:
        enabled: false
      url: ${REDIS_URL:redis://localhost:6379}

  config:
    import:
      - auth-values.yaml
      - test-values.yaml