auth:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}
  user_service:
    password:
      encryption:
        key: ${PASSWORD_ENCRYPTION_KEY} #AES Key

telegram:
  bot:
    message:
      height: ${TELEGRAM_BOT_MESSAGE_MAX_HEIGHT:100}
      limit: ${TELEGRAM_BOT_MESSAGE_COUNT_LIMIT:50}
ubi:
  urls:
    authorization: ${UBI_AUTH_URL:https://public-ubiservices.ubi.com/v3/profiles/sessions}
    twoFaCodeToSMS: ${UBI_TWO_FA_CODE_TO_SMS_URL:https://public-ubiservices.ubi.com/v3/profiles/me/2facode}
  session:
    contentType: ${UBI_CONTENT_TYPE:application/json}
    userAgent: ${UBI_USER_AGENT:UbiServices_SDK_2020.Release.58_PC64_ansi_static}
    twoFaAppId: ${UBI_2FA_APP_ID:685a3038-2b04-47ee-9c5a-6403381a46aa}
    trustedDeviceId: ${UBI_TRUSTED_DEVICE_ID:16a2c7f446d2fcb5b92d0efee317da39}
    trustedDeviceFriendlyName: ${UBI_TRUSTED_DEVICE_FRIENDLY_NAME:Opera 114.0.0.0, Windows 10}
    minUncommonPrice: ${UBI_MIN_UNCOMMON_PRICE:10}
    maxUncommonPrice: ${UBI_MAX_UNCOMMON_PRICE:25_000}
    minRarePrice: ${UBI_MIN_RARE_PRICE:10}
    maxRarePrice: ${UBI_MAX_RARE_PRICE:250_000}
    minEpicPrice: ${UBI_MIN_EPIC_PRICE:10}
    maxEpicPrice: ${UBI_MAX_EPIC_PRICE:1_000_000}
    minLegendaryPrice: ${UBI_MIN_LEGENDARY_PRICE:10}
    maxLegendaryPrice: ${UBI_MAX_LEGENDARY_PRICE:1_000_000}

server:
  port: ${SERVER_PORT:8087}

logging:
  level:
    github: \${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper
  data:
    redis:
      repositories:
        enabled: false
      url: redis://${REDIS_SERVER_HOST:localhost}:${REDIS_SERVER_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import:
      - auth-values.yaml
      - test-values.yaml