ubi:
  session:
    minUncommonPrice: 10
    maxUncommonPrice: 25_000
    minRarePrice: 10
    maxRarePrice: 250_000
    minEpicPrice: 10
    maxEpicPrice: 1_000_000
    minLegendaryPrice: 10
    maxLegendaryPrice: 1_000_000

server:
  port: 8083

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}

logging:
  level:
    github: debug
    org:
      springframework:
        data:
          neo4j:
            cypher:
              unrecognized: off
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: r6s-helper-items-stats-recalculator
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:r6s-helper-items-stats-fetcher}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import:
      - test-values.yaml