ubi:
  session:
    minUncommonPrice: ${UBI_MIN_UNCOMMON_PRICE:10}
    maxUncommonPrice: ${UBI_MAX_UNCOMMON_PRICE:25000}
    minRarePrice: ${UBI_MIN_RARE_PRICE:10}
    maxRarePrice: ${UBI_MAX_RARE_PRICE:250000}
    minEpicPrice: ${UBI_MIN_EPIC_PRICE:10}
    maxEpicPrice: ${UBI_MAX_EPIC_PRICE:1000000}
    minLegendaryPrice: ${UBI_MIN_LEGENDARY_PRICE:10}
    maxLegendaryPrice: ${UBI_MAX_LEGENDARY_PRICE:1000000}

server:
  port: ${SERVER_PORT:8084}

app:
  scheduling:
    enabled: ${SCHEDULING_ENABLED:true}
    items:
      fixedRate: ${SCHEDULING_FIXED_DELAY_ITEMS:180000}
      initialDelay: ${SCHEDULING_INITIAL_DELAY_ITEMS:0}

    current_prices:
      fixedRate: ${SCHEDULING_FIXED_DELAY_CURRENT_PRICES:60000}
      initialDelay: ${SCHEDULING_INITIAL_DELAY_CURRENT_PRICES:0}

logging:
  level:
    github: \${LOGGING_LEVEL:debug}
  file:
    name: ./logs/${LOG_FILE_DIRECTORY:prod}/${spring.application.name}.log

spring:
  application:
    name: r6s-helper-items-stats-recalculator
  data:
    redis:
      repositories:
        enabled: false
      url: redis://${REDIS_SERVER_HOST:localhost}:${REDIS_SERVER_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST:localhost}:${POSTGRES_SERVER_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import:
      - test-values.yaml